'use client';
import { useEffect, useState } from 'react';
import { Flag, Plus, ArrowUpRight, Target, CalendarDays, CircleDollarSign, Trophy, Pencil, Trash2, Check, Activity, ListChecks, ChartNoAxesCombined, MapPinned } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { RoundTracker, type RoundRecord, type RoundHole, type RoundPlayer } from './round-tracker';

type Kind='session'|'task'|'expense'|'milestone'|'round';
type RecordItem={id:string;kind:Kind;title:string;date:string;notes:string;category:string;done:boolean;minutes?:number;cost?:number;score?:number;holes?:'9'|'18';carry?:number;speed?:number;club?:string;holeCount?:'9'|'18';roundHoles?:RoundHole[];players?:RoundPlayer[]};
const names:Record<Kind,string>={session:'session',task:'task',expense:'expense',milestone:'milestone',round:'round'};
const options:Record<Kind,string[]>={session:['Simulator','Range','Course round','Lesson','Short game','Putting'],task:['Next session','This week','Later'],expense:['Practice','Green fees','Lessons','Equipment','Membership','Other'],milestone:['Practice','Scoring','Ball striking','Distance','Consistency'],round:['On course']};
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Brisbane',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function day(s:string){return new Date(s+'T12:00:00Z');}
function pretty(s:string){return s?day(s).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'No date set';}
const aud=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:2}).format(n);
const starter:RecordItem[]=[
{id:'suggested-baseline',kind:'task',title:'Capture a starting baseline',date:'',notes:'At your next simulator session, record a representative set with driver and 7-iron. Log average carry, club speed and the main miss. Keep all shots in the sample.',category:'Next session',done:false},
{id:'suggested-contact',kind:'task',title:'Track strike consistency',date:'',notes:'Use a fixed target and record how many of 10 iron shots have solid contact. Add the result to your session notes so you can compare next time.',category:'This week',done:false},
{id:'suggested-round',kind:'task',title:'Log a complete on-course score',date:'',notes:'Record every stroke, including penalties, plus putting and lost-ball notes. Keep simulator rounds separate from on-course scores.',category:'Later',done:false},
{id:'suggested-90',kind:'milestone',title:'Break 90 on the course',date:'',notes:'Score 89 or less over a complete 18-hole on-course round, counting all strokes and penalties.',category:'Scoring',done:false},
{id:'suggested-100',kind:'milestone',title:'Break 100 on the course',date:'',notes:'Score 99 or less over a complete 18-hole on-course round.',category:'Scoring',done:false},
{id:'suggested-routine',kind:'milestone',title:'Build a four-week practice routine',date:'',notes:'Attend at least two practice sessions a week for four consecutive weeks.',category:'Consistency',done:false}
];
export default function Home(){
 const [records,setRecords]=useState<RecordItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview'),[draft,setDraft]=useState<RecordItem|null>(null),[removing,setRemoving]=useState<RecordItem|null>(null),[filter,setFilter]=useState('All'),[saved,setSaved]=useState(false);
 const refresh=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/records');if(!r.ok)throw new Error('Your records could not be loaded. Please retry.');setRecords(await r.json());}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
 useEffect(()=>{void refresh();},[]);
 const mutate=async(r:RecordItem)=>{const res=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});const data:any=await res.json();if(!res.ok)throw new Error(data.error||'Could not save');setRecords(prev=>[...prev.filter(x=>x.id!==r.id),data]);setSaved(true);return data;};
 async function save(){if(!draft)return;setBusy(true);setError('');try{await mutate(draft);setDraft(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function toggle(r:RecordItem){setBusy(true);setError('');try{await mutate({...r,done:!r.done});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!removing)return;setBusy(true);setError('');try{const r=await fetch('/api/records?id='+encodeURIComponent(removing.id),{method:'DELETE'});if(!r.ok)throw new Error('Could not delete. Please retry.');setRecords(prev=>prev.filter(x=>x.id!==removing.id));setRemoving(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function add(kind:Kind){setError('');setDraft({id:Array.from(crypto.getRandomValues(new Uint8Array(16)), b=>b.toString(16).padStart(2,'0')).join(''),kind,title:'',date:kind==='task'||kind==='milestone'?'':today(),notes:'',category:options[kind][0],done:false,...(kind==='session'?{holes:'18' as const,club:'Driver'}:{})});}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'start_golf_entry',title:'Start a golf entry',description:'Open the golf entry form for user review. Does not save a record.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['session','task','expense','milestone']}},required:['kind'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||!['session','task','expense','milestone'].includes(input.kind))throw new Error('Invalid entry kind');add(input.kind);return{status:'form_opened',kind:input.kind};}},{signal:lifecycle.signal})).catch(console.error);return()=>lifecycle.abort();},[]);
 const sessions=records.filter(x=>x.kind==='session').sort((a,b)=>b.date.localeCompare(a.date));
 const tasks=records.filter(x=>x.kind==='task').sort((a,b)=>Number(a.done)-Number(b.done)||options.task.indexOf(a.category)-options.task.indexOf(b.category)||(a.date||'9999').localeCompare(b.date||'9999'));
 const expenses=records.filter(x=>x.kind==='expense').sort((a,b)=>b.date.localeCompare(a.date));
 const goals=records.filter(x=>x.kind==='milestone');
 const trackedRounds=records.filter((x):x is RecordItem&RoundRecord=>x.kind==='round'&&!!x.holeCount&&!!x.roundHoles);
 const completeTrackedRounds=trackedRounds.filter(x=>x.holeCount==='18'&&x.roundHoles.every(h=>h.score!==null));
 const legacyRounds=sessions.filter(x=>x.category==='Course round'&&x.holes==='18'&&x.score!==undefined);
 const scoringRounds=[...legacyRounds.map(x=>({id:x.id,date:x.date,score:x.score!})),...completeTrackedRounds.map(x=>({id:x.id,date:x.date,score:x.roundHoles.reduce((s,h)=>s+(h.score||0),0)}))].sort((a,b)=>a.date.localeCompare(b.date));
 const best=scoringRounds.length?Math.min(...scoringRounds.map(x=>x.score)):null;
 const now=today(),month=now.slice(0,7),monday=day(now);monday.setUTCDate(monday.getUTCDate()-((monday.getUTCDay()+6)%7));const weekStart=monday.toISOString().slice(0,10);
 const practice=sessions.filter(x=>x.category!=='Course round'),weekCount=practice.filter(x=>x.date>=weekStart&&x.date<=now).length;
 const total=expenses.reduce((s,x)=>s+(x.cost||0),0)+sessions.reduce((s,x)=>s+(x.cost||0),0);
 const monthSpend=[...expenses,...sessions].filter(x=>x.date.startsWith(month)).reduce((s,x)=>s+(x.cost||0),0);
 const next=tasks.find(x=>!x.done);
 const weeks=Array.from({length:8},(_,i)=>{const start=new Date(monday);start.setUTCDate(start.getUTCDate()-(7-i)*7);const end=new Date(start);end.setUTCDate(end.getUTCDate()+7);return{label:start.toLocaleDateString('en-AU',{day:'numeric',month:'short',timeZone:'UTC'}),count:practice.filter(s=>s.date>=start.toISOString().slice(0,10)&&s.date<end.toISOString().slice(0,10)&&s.date<=now).length};});
 const edit=(r:RecordItem)=>{setError('');setDraft({...r});};
 const taskRow=(r:RecordItem)=><div className={'task '+(r.done?'done':'')} key={r.id}><Checkbox checked={r.done} disabled={busy} onCheckedChange={()=>void toggle(r)} aria-label={'Mark '+r.title+(r.done?' incomplete':' complete')}/><main><h3>{r.title}</h3><p className="muted">{r.category}{r.date?' · '+pretty(r.date):''}</p>{r.notes&&<p className="muted">{r.notes}</p>}</main><button className="iconbtn" aria-label={'Edit '+r.title} onClick={()=>edit(r)}><Pencil size={16}/></button></div>;
 const empty=(title:string,detail:string,kind?:Kind)=><div className="empty"><Flag size={28}/><h3>{title}</h3><p className="muted">{detail}</p>{kind&&<button className="button" onClick={()=>add(kind)}><Plus size={15}/>Add {names[kind]}</button>}</div>;
 async function useStarter(){setBusy(true);setError('');try{for(const r of starter){if(!records.some(x=>x.id===r.id))await mutate(r);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function chart(){if(!scoringRounds.length)return empty('No baseline. Yet.','Complete an 18-hole scorecard to start your score trend.');const vals=scoringRounds.slice(-12),hi=Math.max(110,...vals.map(x=>x.score))+5,lo=Math.min(80,...vals.map(x=>x.score))-5;const x=(i:number)=>40+i*500/Math.max(vals.length-1,1),y=(v:number)=>150-(v-lo)/(hi-lo)*120;return <><svg className="trend" viewBox="0 0 580 180" role="img" aria-label={'18-hole course scores: '+vals.map(v=>v.score+' on '+pretty(v.date)).join(', ')}><line x1="35" x2="555" y1={y(90)} y2={y(90)} stroke="#a8b899" strokeDasharray="5 5"/><text x="555" y={y(90)-8} fill="#b2bdac" fontSize="12" textAnchor="end">90 target</text><polyline points={vals.map((v,i)=>`${x(i)},${y(v.score)}`).join(' ')} fill="none" stroke="#c8f763" strokeWidth="3"/>{vals.map((v,i)=><g key={v.id}><circle cx={x(i)} cy={y(v.score)} r="5" fill="#c8f763"/><text x={x(i)} y={y(v.score)-12} textAnchor="middle" fill="#eef2e7" fontSize="13">{v.score}</text></g>)}</svg><div className="chartlabels"><span>{pretty(vals[0].date)}</span><span>{pretty(vals[vals.length-1].date)}</span></div></>;}
 return <div className="shell"><header className="brandbar"><div className="brand"><span className="brandmark"><Flag size={23}/></span>Golf Progress</div><span className="muted">GOLD COAST / AUSTRALIA</span><span className="edition">EST. 2026 <span> / </span> YOUR GAME</span></header><div className="heading"><div><div className="eyebrow">PERSONAL PERFORMANCE CENTRE</div><h1>The training room.</h1><span className="muted">Your next session starts here.</span></div><button className="button primary" disabled={loading||!!error&&!records.length} onClick={()=>add('session')}><Plus size={17}/>Log a session</button></div>
 <Tabs className="workspace" orientation="vertical" value={tab} onValueChange={v=>{setTab(v);setFilter('All');}}><TabsList className="nav" aria-label="Golf journal sections"><span className="navlabel">YOUR WORKSPACE</span>{[['overview','Overview',ChartNoAxesCombined],['rounds','Rounds',MapPinned],['sessions','Sessions',CalendarDays],['tasks','Next tasks',ListChecks],['expenses','Spending',CircleDollarSign],['milestones','Milestones',Trophy]].map(([key,label,Icon])=><TabsTrigger key={key as string} value={key as string}>{typeof Icon!=='string'&&<Icon size={16}/>} {label as string}</TabsTrigger>)}<div className="railgoal"><Flag size={20}/><span>THE MISSION</span><strong>Break 90.</strong><small>2–3 sessions / week</small></div></TabsList>
 {error&&!draft&&<div className="error" role="alert">{error} <button onClick={()=>void refresh()} className="button small">Retry loading</button></div>}
 {loading?<div className="loading muted">Loading your golf journal…</div>:<>
 <TabsContent value="overview">
 <div className="layoutgrid featuregrid"><section className="panel focus"><div className="row"><span className="eyebrow">01 / NEXT UP</span><Target size={23}/></div><h2>{next?.title||'Find your starting point.'}</h2><p className="muted">{next?.notes||'Build your next practice around one measurable task. Your starter plan covers simulator data, strike consistency and a first complete course score.'}</p><div className="row"><span className="muted">{next?.category||'Suggested starting plan'}</span>{next?<button className="button" onClick={()=>setTab('tasks')}>View tasks <ArrowUpRight size={17}/></button>:<button className="button" disabled={busy} onClick={()=>void useStarter()}>{busy?'Adding…':'Add starter plan'}<Plus size={17}/></button>}</div></section><section className="panel goalcard mission"><div className="sectionhead"><h2>THE MISSION</h2><Flag size={18}/></div><div className="row"><div className="missionnumber"><span>BREAK</span>90<span className="missionunit">18 HOLES · ON COURSE</span></div></div><p className="muted">89 or better. Every stroke counted.</p><div className="row"><span className="muted">{best===null?'Baseline not yet recorded':best<90?'Goal achieved — keep building!':`${best-89} strokes from your best`}</span><button className="iconbtn" aria-label="View milestones" onClick={()=>setTab('milestones')}><ArrowUpRight size={20}/></button></div></section></div>
 <div className="cards"><div className="card"><div className="row"><span className="muted">Practice this week</span><CalendarDays size={17}/></div><strong>{weekCount}<span className="muted"> / 2–3</span></strong><span className="muted">Weekly aim · Mon–Sun</span></div><div className="card"><div className="row"><span className="muted">Best 18-hole score</span><Flag size={17}/></div><strong>{best??'—'}</strong><span className="muted">On-course rounds only</span></div><div className="card"><div className="row"><span className="muted">Practice time</span><Activity size={17}/></div><strong>{(practice.reduce((s,x)=>s+(x.minutes||0),0)/60).toFixed(1)}<span className="muted"> hrs</span></strong><span className="muted">{practice.length} practice sessions logged</span></div><div className="card"><div className="row"><span className="muted">Spent this month</span><CircleDollarSign size={17}/></div><strong>{aud(monthSpend)}</strong><span className="muted">{aud(total)} lifetime · AUD</span></div></div>
 <div className="layoutgrid"><section className="panel"><div className="sectionhead"><h2>Scoring progress</h2><span className="badge">ON COURSE · 18H</span></div>{chart()}</section><section className="panel"><div className="sectionhead"><h2>Practice rhythm</h2></div><span className="muted">Practice sessions over the last eight weeks</span><div className="weeks">{weeks.map(w=><div className="week" key={w.label}><span style={{'--h':`${Math.max(4,w.count/Math.max(3,...weeks.map(w=>w.count))*65)}px`} as any} title={`${w.count} sessions`}></span><b>{w.count}</b></div>)}</div><div className="chartlabels"><span>{weeks[0].label}</span><span>This week</span></div><Progress className="bar" value={Math.min(100,weekCount/2*100)}/><span className="muted">{weekCount>=2?'Weekly minimum reached.':`${Math.max(0,2-weekCount)} more to reach your weekly minimum.`}</span></section></div>
 <div className="layoutgrid"><section className="panel"><div className="sectionhead"><h2>Next tasks</h2><button className="button small" onClick={()=>add('task')}><Plus size={15}/>Add task</button></div>{tasks.filter(t=>!t.done).slice(0,3).map(taskRow)}{!tasks.some(t=>!t.done)&&empty('Pick your next challenge','Add your next practice task, or use the starter plan above.')}</section><section className="panel"><div className="sectionhead"><h2>Latest session</h2><button className="iconbtn" aria-label="View all sessions" onClick={()=>setTab('sessions')}><ArrowUpRight size={20}/></button></div>{sessions[0]?<><span className="badge">{sessions[0].category}</span><h3 style={{marginTop:15}}>{sessions[0].title}</h3><p className="muted">{pretty(sessions[0].date)} · {sessions[0].minutes||0} minutes</p><p>{sessions[0].notes||'No notes recorded.'}</p><button className="button small" onClick={()=>edit(sessions[0])}>View / edit</button></>:empty('No sessions logged yet','Add your simulator, range, lesson or on-course sessions.','session')}</section></div></TabsContent>
 <TabsContent value="rounds"><RoundTracker rounds={trackedRounds} onSave={mutate} onDelete={setRemoving} today={today} pretty={pretty}/></TabsContent>
 <TabsContent value="sessions"><div className="heading"><div><h2>The session log</h2><p className="muted">Attendance, results and the one thing to take into your next session.</p></div><button className="button primary" onClick={()=>add('session')}><Plus size={16}/>Log session</button></div><div className="toolbar">{['All','Simulator','Range','Course round','Lesson','Short game','Putting'].map(f=><button className={'button small '+(filter===f?'primary':'')} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="ledger">{sessions.filter(s=>filter==='All'||s.category===filter).map(s=><article className="entry" key={s.id}><div className="datebox">{day(s.date).getUTCDate()}<br/>{day(s.date).toLocaleDateString('en-AU',{month:'short',timeZone:'UTC'})}</div><main><div className="row"><h3>{s.title}</h3><span className="badge">{s.category}</span></div><div className="pillrow"><span className="muted">{pretty(s.date)}{s.minutes!==undefined?` · ${s.minutes} min`:''}</span>{s.score!==undefined&&<span className="badge">{s.score} strokes · {s.holes} holes</span>}{s.carry!==undefined&&<span className="badge">{s.club}: {s.carry} m carry</span>}{s.speed!==undefined&&<span className="badge">{s.speed} mph club speed</span>}{s.cost!==undefined&&<span className="muted">{aud(s.cost)}</span>}</div>{s.notes&&<p className="muted">{s.notes}</p>}</main><button className="iconbtn" aria-label={'Edit '+s.title} onClick={()=>edit(s)}><Pencil size={17}/></button></article>)}</div>{!sessions.filter(s=>filter==='All'||s.category===filter).length&&empty('No sessions here yet','Every session you log adds to your story.','session')}</TabsContent>
 <TabsContent value="tasks"><div className="heading"><div><h2>A plan for your next session</h2><p className="muted">{tasks.filter(t=>t.done).length} completed · {tasks.filter(t=>!t.done).length} to go</p></div><button className="button primary" onClick={()=>add('task')}><Plus size={16}/>Add task</button></div>{!tasks.length?<section className="panel">{empty('Turn practice into progress','Add your own tasks, or start with a baseline and consistency plan.','task')}<div style={{textAlign:'center'}}><button className="button" disabled={busy} onClick={()=>void useStarter()}>Add starter plan</button></div></section>:<section className="panel">{tasks.map(taskRow)}</section>}</TabsContent>
 <TabsContent value="expenses"><div className="heading"><div><h2>Investment in your game</h2><p className="muted">Australian dollars. Session costs are included automatically.</p></div><button className="button primary" onClick={()=>add('expense')}><Plus size={16}/>Add expense</button></div><div className="layoutgrid"><section className="panel"><div className="eyebrow">Total recorded spending</div><div className="goalnumber" style={{margin:'18px 0'}}>{aud(total)}</div><p className="muted">{aud(monthSpend)} this month</p><div className="row"><span>Session fees</span><strong>{aud(sessions.reduce((s,x)=>s+(x.cost||0),0))}</strong></div><div className="moneybar"><div style={{width:`${total?sessions.reduce((s,x)=>s+(x.cost||0),0)/total*100:0}%`}}/></div>{options.expense.map(c=>{const sum=expenses.filter(e=>e.category===c).reduce((s,e)=>s+(e.cost||0),0);return <div key={c}><div className="row"><span className="muted">{c}</span><strong>{aud(sum)}</strong></div><div className="moneybar"><div style={{width:`${total?sum/total*100:0}%`}}/></div></div>;})}</section><section><h2 className="subhead">Expense history</h2><p className="muted">If you added a cost to a session, don't enter it again here.</p><div className="ledger">{[...expenses,...sessions.filter(s=>s.cost!==undefined&&s.cost>0)].sort((a,b)=>b.date.localeCompare(a.date)).map(e=><article className="entry" key={e.id}><main><h3>{e.title}</h3><p className="muted">{pretty(e.date)} · {e.kind==='session'?'Session fee':e.category}</p>{e.kind==='expense'&&e.notes&&<p className="muted">{e.notes}</p>}</main><strong>{aud(e.cost||0)}</strong><button className="iconbtn" aria-label={'Edit '+e.title} onClick={()=>edit(e)}><Pencil size={16}/></button></article>)}</div>{!total&&!expenses.length&&empty('A clear picture of your golf spend','Track equipment, memberships, green fees and lessons.','expense')}</section></div></TabsContent>
 <TabsContent value="milestones"><div className="heading"><div><h2>The milestones</h2><p className="muted">{goals.filter(g=>g.done).length} of {goals.length} milestones achieved. Mark them complete when you meet the criteria.</p></div><button className="button primary" onClick={()=>add('milestone')}><Plus size={16}/>Add milestone</button></div><div className="layoutgrid">{goals.map(g=><section className="panel goalcard" key={g.id}><div className="sectionhead"><span className="badge">{g.category}</span><button className="iconbtn" aria-label={'Edit '+g.title} onClick={()=>edit(g)}><Pencil size={16}/></button></div><h2>{g.title}</h2><p className="muted">{g.notes}</p>{g.date&&<p className="muted">Target: {pretty(g.date)}</p>}<button className={'button '+(g.done?'primary':'')} disabled={busy} onClick={()=>void toggle(g)}>{g.done?<><Check size={16}/>Achieved · undo</>:<><Trophy size={16}/>Mark achieved</>}</button></section>)}</div>{!goals.length&&<section className="panel">{empty('Give the progress a destination','Add milestones for scoring, contact or consistent practice.','milestone')}<div style={{textAlign:'center'}}><button className="button" disabled={busy} onClick={()=>void useStarter()}>Add starter plan</button></div></section>}</TabsContent>
 </>}
 </Tabs><footer className="footer"><span>Golf Progress · Distances in metres · Speed in mph · Costs in AUD</span><span>{saved?'Changes saved':'Your personal golf journal'}</span></footer>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy){setDraft(null);setError('');}}}><DialogContent className="modal"><DialogTitle>{draft&&records.some(r=>r.id===draft.id)?'Edit':'Add'} {draft?names[draft.kind]:''}</DialogTitle><DialogDescription>{draft?.kind==='session'?'Capture the session, results and what to work on next.':draft?.kind==='expense'?'Record a purchase or fee not already entered with a session.':'Make the outcome specific enough to know when it is done.'}</DialogDescription>{draft&&<form onSubmit={e=>{e.preventDefault();void save();}}><div className="formgrid"><label className="field span2">{draft.kind==='session'?'Venue / session title':'Title'}<input required maxLength={200} value={draft.title} placeholder={draft.kind==='session'?'e.g. Birdie Cage · driver baseline':'What are you tracking?'} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field">{draft.kind==='task'?'Priority':'Category'}<Select value={draft.category} onValueChange={v=>setDraft({...draft,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options[draft.kind].map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select></label><label className="field">{draft.kind==='task'?'Due date (optional)':draft.kind==='milestone'?'Target date (optional)':'Date'}<input type="date" required={draft.kind==='session'||draft.kind==='expense'} max={draft.kind==='session'||draft.kind==='expense'?today():undefined} value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>
 {draft.kind==='session'&&<><label className="field">Duration (minutes)<input type="number" min="0" max="1440" value={draft.minutes??''} onChange={e=>setDraft({...draft,minutes:e.target.value===''?undefined:Number(e.target.value)})}/></label><label className="field">Session cost (AUD)<input type="number" min="0" max="1000000" step=".01" value={draft.cost??''} onChange={e=>setDraft({...draft,cost:e.target.value===''?undefined:Number(e.target.value)})}/></label>{['Course round','Simulator'].includes(draft.category)&&<><label className="field">Score (optional)<input type="number" min="1" max="300" value={draft.score??''} onChange={e=>setDraft({...draft,score:e.target.value===''?undefined:Number(e.target.value)})}/></label><label className="field">Holes<Select value={draft.holes||'18'} onValueChange={v=>setDraft({...draft,holes:v as '9'|'18'})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="9">9 holes</SelectItem><SelectItem value="18">18 holes</SelectItem></SelectContent></Select></label></>}<label className="field span2">Club measured (optional)<input value={draft.club||''} placeholder="Driver, 7-iron…" onChange={e=>setDraft({...draft,club:e.target.value})}/></label><label className="field">Average carry (m)<input type="number" step=".1" min="0" max="600" value={draft.carry??''} onChange={e=>setDraft({...draft,carry:e.target.value===''?undefined:Number(e.target.value)})}/></label><label className="field">Club speed (mph)<input type="number" step=".1" min="0" max="250" value={draft.speed??''} onChange={e=>setDraft({...draft,speed:e.target.value===''?undefined:Number(e.target.value)})}/></label></>}
 {draft.kind==='expense'&&<label className="field span2">Amount (AUD)<input type="number" min="0" max="1000000" step=".01" required value={draft.cost??''} onChange={e=>setDraft({...draft,cost:e.target.value===''?undefined:Number(e.target.value)})}/></label>}
 <label className="field span2">{draft.kind==='milestone'?'Success criteria / notes':draft.kind==='task'?'What to do / success criteria':'Notes and next focus'}<textarea maxLength={5000} value={draft.notes} placeholder={draft.kind==='session'?'What improved? Main miss? What will you work on next?':''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div>{error&&<div role="alert" className="error">{error}</div>}<div className="row" style={{marginTop:22}}>{records.some(r=>r.id===draft.id)?<button type="button" className="iconbtn" disabled={busy} onClick={()=>{setRemoving(draft);setDraft(null);}}><Trash2 size={19}/><span className="sr-only">Delete record</span></button>:<span/>}<button className="button primary" disabled={busy} type="submit">{busy?'Saving…':'Save '+names[draft.kind]}</button></div></form>}</DialogContent></Dialog>
 <AlertDialog open={!!removing} onOpenChange={v=>{if(!v&&!busy)setRemoving(null);}}><AlertDialogContent><AlertDialogTitle>Delete this {removing?.kind}?</AlertDialogTitle><AlertDialogDescription>“{removing?.title}” will be permanently removed from your journal.</AlertDialogDescription>{error&&<p role="alert" className="error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void remove();}}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
