'use client';
import { useMemo, useState } from 'react';
import { Flag, MapPinned, Plus, Trash2, UserPlus, Users, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

export type RoundHole={hole:number;par:number;score:number|null};
export type RoundPlayer={id:string;name:string;scores:(number|null)[]};
export type RoundRecord={id:string;kind:'round';title:string;date:string;notes:string;category:string;done:boolean;holeCount:'9'|'18';roundHoles:RoundHole[];players?:RoundPlayer[]};
type Props={rounds:RoundRecord[];onSave:(round:RoundRecord)=>Promise<unknown>;onDelete:(round:RoundRecord)=>void;today:()=>string;pretty:(date:string)=>string};

const blankHoles=(count:number):RoundHole[]=>Array.from({length:count},(_,i)=>({hole:i+1,par:4,score:null}));
const uid=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
const signed=(n:number)=>n===0?'E':n>0?`+${n}`:`${n}`;
const scoreFor=(round:RoundRecord,index:number)=>round.players?.[0]?.scores[index]??round.roundHoles[index]?.score??null;
const hydratePlayers=(round:RoundRecord,count:number):RoundPlayer[]=>round.players?.length
 ?round.players.map(player=>({...player,scores:Array.from({length:count},(_,i)=>player.scores[i]??null)}))
 :[{id:uid(),name:'Me',scores:Array.from({length:count},(_,i)=>round.roundHoles[i]?.score??null)}];

export function RoundTracker({rounds,onSave,onDelete,today,pretty}:Props){
 const [draft,setDraft]=useState<RoundRecord|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(''),[courseChoice,setCourseChoice]=useState('__new');
 const courses=useMemo(()=>{const found=new Map<string,{title:string;holeCount:'9'|'18';pars:number[]}>();rounds.slice().sort((a,b)=>b.date.localeCompare(a.date)).forEach(round=>{const key=round.title.trim().toLocaleLowerCase();if(key&&!found.has(key))found.set(key,{title:round.title,holeCount:round.holeCount,pars:round.roundHoles.map(h=>h.par)});});return [...found.values()].sort((a,b)=>a.title.localeCompare(b.title));},[rounds]);
 const playerTotals=useMemo(()=>{if(!draft)return[];return (draft.players||[]).map(player=>{const played=player.scores.map((score,i)=>({score,par:draft.roundHoles[i]?.par||4})).filter(x=>x.score!==null);const par=played.reduce((s,h)=>s+h.par,0),score=played.reduce((s,h)=>s+(h.score||0),0);return{id:player.id,name:player.name,played:played.length,par,score,toPar:score-par};});},[draft]);
 function start(round?:RoundRecord){setError('');if(round){const count=Number(round.holeCount);setDraft({...round,roundHoles:round.roundHoles.map(h=>({...h})),players:hydratePlayers(round,count)});setCourseChoice(round.title);}else{const holes=blankHoles(18);setDraft({id:uid(),kind:'round',title:'',date:today(),notes:'',category:'On course',done:false,holeCount:'18',roundHoles:holes,players:[{id:uid(),name:'Me',scores:holes.map(()=>null)}]});setCourseChoice('__new');}}
 function resize(value:'9'|'18',pars?:number[]){if(!draft)return;const count=Number(value);const roundHoles=Array.from({length:count},(_,i)=>draft.roundHoles[i]?{...draft.roundHoles[i],hole:i+1,par:pars?.[i]??draft.roundHoles[i].par}:{hole:i+1,par:pars?.[i]??4,score:null});const players=(draft.players||[]).map(player=>({...player,scores:Array.from({length:count},(_,i)=>player.scores[i]??null)}));setDraft({...draft,holeCount:value,roundHoles,players});}
 function chooseCourse(value:string){if(!draft)return;setCourseChoice(value);if(value==='__new'){setDraft({...draft,title:''});return;}const course=courses.find(item=>item.title===value);if(!course)return;const count=Number(course.holeCount);const roundHoles=Array.from({length:count},(_,i)=>({hole:i+1,par:course.pars[i]??4,score:draft.players?.[0]?.scores[i]??draft.roundHoles[i]?.score??null}));const players=(draft.players||[]).map(player=>({...player,scores:Array.from({length:count},(_,i)=>player.scores[i]??null)}));setDraft({...draft,title:course.title,holeCount:course.holeCount,roundHoles,players});}
 function changePar(index:number,value:string){if(!draft)return;setDraft({...draft,roundHoles:draft.roundHoles.map((hole,i)=>i===index?{...hole,par:Number(value)}:hole)});}
 function changeScore(playerId:string,index:number,value:string){if(!draft)return;const score=value===''?null:Number(value);const players=(draft.players||[]).map(player=>player.id===playerId?{...player,scores:player.scores.map((item,i)=>i===index?score:item)}:player);setDraft({...draft,players,roundHoles:draft.roundHoles.map((hole,i)=>i===index?{...hole,score:players[0]?.scores[i]??null}:hole)});}
 function addPlayer(){if(!draft||(draft.players?.length||0)>=8)return;const number=(draft.players?.length||0)+1;setDraft({...draft,players:[...(draft.players||[]),{id:uid(),name:`Player ${number}`,scores:draft.roundHoles.map(()=>null)}]});}
 function updatePlayerName(playerId:string,name:string){if(!draft)return;setDraft({...draft,players:(draft.players||[]).map(player=>player.id===playerId?{...player,name}:player)});}
 function removePlayer(playerId:string){if(!draft||(draft.players?.length||0)<=1)return;setDraft({...draft,players:(draft.players||[]).filter(player=>player.id!==playerId)});}
 async function save(){if(!draft||!draft.title.trim()||!(draft.players||[]).every(player=>player.name.trim()))return;setSaving(true);setError('');try{const primary=draft.players?.[0];const roundHoles=draft.roundHoles.map((hole,i)=>({...hole,score:primary?.scores[i]??hole.score}));await onSave({...draft,title:draft.title.trim(),players:draft.players?.map(player=>({...player,name:player.name.trim()})),roundHoles,done:roundHoles.every(h=>h.score!==null)});setDraft(null);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 const sorted=rounds.slice().sort((a,b)=>b.date.localeCompare(a.date));
 return <div className="rounds-surface"><div className="heading"><div><h2>Round tracker</h2><p className="muted">Reusable courses, player scorecards and hole-by-hole scoring.</p></div><button className="button primary" onClick={()=>start()}><Plus size={16}/>Start a round</button></div>
 {!sorted.length?<section className="panel round-empty"><MapPinned size={34}/><h2>Your next round starts here.</h2><p className="muted">Add the course once, then reuse its par layout whenever you play it again.</p><button className="button primary" onClick={()=>start()}><Plus size={16}/>Create scorecard</button></section>:<div className="round-list">{sorted.map(round=>{const scores=round.roundHoles.map((_,i)=>scoreFor(round,i)),played=scores.filter(score=>score!==null),par=scores.reduce<number>((s,score,i)=>s+(score===null?0:round.roundHoles[i].par),0),score=played.reduce<number>((s,item)=>s+(item||0),0),front=scores.slice(0,9).filter(item=>item!==null),back=scores.slice(9).filter(item=>item!==null),sum=(items:(number|null)[])=>items.reduce<number>((s,item)=>s+(item||0),0),playerCount=round.players?.length||1;return <article className="panel round-card" key={round.id}><div className="round-date"><span>{new Date(round.date+'T12:00:00Z').getUTCDate()}</span>{new Date(round.date+'T12:00:00Z').toLocaleDateString('en-AU',{month:'short',timeZone:'UTC'}).toUpperCase()}</div><main><div className="round-card-head"><div><span className="badge">{round.holeCount} HOLES · {played.length===Number(round.holeCount)?'COMPLETE':'IN PROGRESS'}</span><h2>{round.title}</h2><span className="muted">{pretty(round.date)} · {playerCount} {playerCount===1?'player':'players'}</span></div><button className="button small" onClick={()=>start(round)}>View / edit</button></div><div className="round-mini-grid"><div><span>PAR PLAYED</span><strong>{par||'—'}</strong></div><div><span>YOUR SCORE</span><strong>{score||'—'}</strong></div><div><span>TO PAR</span><strong className={score-par<0?'under':''}>{played.length?signed(score-par):'—'}</strong></div><div><span>OUT</span><strong>{front.length?sum(front):'—'}</strong></div><div><span>IN</span><strong>{back.length?sum(back):'—'}</strong></div></div>{round.notes&&<p className="muted">{round.notes}</p>}</main></article>;})}</div>}
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!saving)setDraft(null);}}><DialogContent className="round-modal"><DialogTitle>{rounds.some(r=>r.id===draft?.id)?'Edit round':'New round'}</DialogTitle><DialogDescription>Save at any point and finish the card later. Your first player drives your personal scoring progress.</DialogDescription>{draft&&<form onSubmit={e=>{e.preventDefault();void save();}}><div className="round-meta">{courses.length?<label className="field">Course<Select value={courseChoice} onValueChange={chooseCourse}><SelectTrigger><SelectValue placeholder="Choose a course"/></SelectTrigger><SelectContent><SelectItem value="__new">Add a new course</SelectItem>{courses.map(course=><SelectItem key={course.title.toLocaleLowerCase()} value={course.title}>{course.title}</SelectItem>)}</SelectContent></Select></label>:null}{(!courses.length||courseChoice==='__new')&&<label className="field">{courses.length?'New course name':'Course'}<input required maxLength={200} autoFocus placeholder="e.g. Boomerang Farm" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>}<label className="field">Date<input required type="date" max={today()} value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="field">Round length<Select value={draft.holeCount} onValueChange={v=>resize(v as '9'|'18')}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="9">9 holes</SelectItem><SelectItem value="18">18 holes</SelectItem></SelectContent></Select></label><label className="field round-notes">Notes<input maxLength={5000} placeholder="Conditions, focus, key takeaway…" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div>
 <section className="players-panel"><div className="sectionhead"><div><h3>Players</h3><p className="muted">The first player is used for your progress charts.</p></div><button type="button" className="button small" onClick={addPlayer} disabled={(draft.players?.length||0)>=8}><UserPlus size={16}/>Add player</button></div><div className="player-list">{(draft.players||[]).map((player,index)=><div className="player-name" key={player.id}><Users size={16}/><input required maxLength={50} aria-label={`Player ${index+1} name`} value={player.name} onChange={e=>updatePlayerName(player.id,e.target.value)}/>{index===0?<span className="badge">YOU</span>:<button type="button" className="iconbtn" aria-label={`Remove ${player.name}`} onClick={()=>removePlayer(player.id)}><X size={17}/></button>}</div>)}</div></section>
 <div className="scorecard-intro"><div><h3>Scorecard</h3><p className="muted">Enter each hole as you play. Course pars will be remembered next time.</p></div><span className="badge">{draft.holeCount} HOLES</span></div><div className="hole-grid">{draft.roundHoles.map((hole,i)=><section className="hole-card" key={hole.hole}><div className="hole-head"><strong>Hole {hole.hole}</strong><label>Par<input aria-label={`Hole ${hole.hole} par`} inputMode="numeric" type="number" min="3" max="6" value={hole.par} onChange={e=>changePar(i,e.target.value)}/></label></div>{(draft.players||[]).map(player=>{const score=player.scores[i],relative=score===null?null:score-hole.par;return <label className="player-score-row" key={player.id}><span>{player.name||'Unnamed player'}<small>{relative===null?'':signed(relative)}</small></span><input aria-label={`Hole ${hole.hole}, ${player.name} score`} inputMode="numeric" type="number" min="1" max="20" placeholder="—" value={score??''} onChange={e=>changeScore(player.id,i,e.target.value)}/></label>;})}</section>)}</div>
 <div className="player-totals">{playerTotals.map((total,index)=><div className="player-total" key={total.id}><span>{total.name||`Player ${index+1}`}</span><strong>{total.played?total.score:'—'}</strong><small>{total.played?`${signed(total.toPar)} · ${total.played}/${draft.holeCount} holes`:'No scores yet'}</small></div>)}</div>{error&&<div className="error" role="alert">{error}</div>}<div className="round-actions">{rounds.some(r=>r.id===draft.id)?<button className="button danger" type="button" disabled={saving} onClick={()=>{onDelete(draft);setDraft(null);}}><Trash2 size={16}/>Delete</button>:<button className="button" type="button" onClick={()=>setDraft(null)}><X size={16}/>Cancel</button>}<button className="button primary" type="submit" disabled={saving||!draft.title.trim()||!(draft.players||[]).every(player=>player.name.trim())}><Flag size={16}/>{saving?'Saving…':'Save scorecard'}</button></div></form>}</DialogContent></Dialog></div>;
}
