'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronRight, Flag, MapPinned, Pencil, Plus, RotateCcw, Trash2, UserPlus, Users, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ActiveRound } from './active-round';
import { goldCoastCourses, type CoursePreset } from '@/lib/course-catalog';
import { calculateRoundSummary, getPlayerHoleStat, hydrateRound, inferRoundStatus, type RoundHole, type RoundRecord } from '@/lib/rounds';
import { displayDistance, distanceLabel, rounded, storeDistance, type DistanceUnit } from '@/lib/preferences';

export type { RoundHole, RoundPlayer, RoundRecord } from '@/lib/rounds';

type Props={rounds:RoundRecord[];onSave:(round:RoundRecord)=>Promise<unknown>;onDelete:(round:RoundRecord)=>void;today:()=>string;pretty:(date:string)=>string;distanceUnit:DistanceUnit};
type CourseConfig={key:string;courseKey:string;title:string;teeName:string;holeCount:'9'|'18';holes:{par:number;distance?:number}[];sourceUrl?:string};
type CourseGroup={key:string;title:string;options:CourseConfig[]};
const uid=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),byte=>byte.toString(16).padStart(2,'0')).join('');
const signed=(value:number)=>value===0?'E':value>0?`+${value}`:`${value}`;
const courseIdentity=(name:string)=>name.trim().toLocaleLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const cacheKey='golf-progress-active-round';

function blankRound(today:string):RoundRecord{
 const players=[{id:uid(),name:'Me',scores:Array.from({length:18},()=>null)}];
 return hydrateRound({id:uid(),kind:'round',title:'',date:today,notes:'',category:'On course',done:false,holeCount:'18',roundHoles:Array.from({length:18},(_,index)=>({hole:index+1,par:4,score:null})),players,status:'setup',activeHole:1});
}

export function RoundTracker({rounds,onSave,onDelete,today,pretty,distanceUnit}:Props){
 const [setup,setSetup]=useState<RoundRecord|null>(null),[review,setReview]=useState<RoundRecord|null>(null),[active,setActive]=useState<RoundRecord|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(''),[courseChoice,setCourseChoice]=useState('__new'),[teeChoice,setTeeChoice]=useState(''),[saveState,setSaveState]=useState<'saved'|'saving'|'error'>('saved'),[reviewPlayerId,setReviewPlayerId]=useState('');
 const [courseCatalog,setCourseCatalog]=useState<readonly CoursePreset[]>(goldCoastCourses);
 const saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),pendingSave=useRef<RoundRecord|null>(null),saveInFlight=useRef(false),saveHandler=useRef(onSave);
 useEffect(()=>{saveHandler.current=onSave;},[onSave]);
 useEffect(()=>()=>{if(saveTimer.current)clearTimeout(saveTimer.current);if(pendingSave.current)void saveHandler.current(pendingSave.current);},[]);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/courses',{signal:controller.signal}).then(async response=>{if(!response.ok)return;const catalog=await response.json() as CoursePreset[];if(Array.isArray(catalog)&&catalog.length)setCourseCatalog(catalog);}).catch(()=>{});return()=>controller.abort();},[]);

 const courses=useMemo(()=>{
  const presets:CourseConfig[]=courseCatalog.map(course=>({
   key:`preset:${course.id}`,courseKey:`course:${courseIdentity(course.name)}`,title:course.name,teeName:course.teeName,
   holeCount:course.pars.length===9?'9':'18',sourceUrl:course.sourceUrl,
   holes:course.pars.map((par,index)=>({par,distance:course.distancesMetres?.[index]})),
  }));
  const presetNames=new Set(presets.map(course=>`${course.title.trim().toLocaleLowerCase()}::${course.teeName.toLocaleLowerCase()}`));
  const played=new Map<string,CourseConfig>();
  rounds.slice().sort((a,b)=>b.date.localeCompare(a.date)).forEach(source=>{
   const round=hydrateRound(source),teeName=round.teeName?.trim()??'';
   const identity=`${round.title.trim().toLocaleLowerCase()}::${teeName.toLocaleLowerCase()}`;
   if(round.title.trim()&&!presetNames.has(identity)&&!played.has(identity))
    played.set(identity,{key:`played:${identity}`,courseKey:`course:${courseIdentity(round.title)}`,title:round.title,teeName,holeCount:round.holeCount,holes:round.roundHoles.map(hole=>({par:hole.par,distance:hole.distance}))});
  });
  return [...presets,...played.values()].sort((a,b)=>a.title.localeCompare(b.title)||a.teeName.localeCompare(b.teeName));
 },[courseCatalog,rounds]);
 const courseGroups=useMemo(()=>{const groups=new Map<string,CourseGroup>(),length=(course:CourseConfig)=>course.holes.reduce((total,hole)=>total+(hole.distance??0),0);courses.forEach(course=>{const group=groups.get(course.courseKey);if(group)group.options.push(course);else groups.set(course.courseKey,{key:course.courseKey,title:course.title,options:[course]});});return [...groups.values()].map(group=>({...group,options:group.options.sort((a,b)=>length(b)-length(a)||a.teeName.localeCompare(b.teeName))})).sort((a,b)=>a.title.localeCompare(b.title));},[courses]);
 const selectedGroup=courseGroups.find(group=>group.key===courseChoice),selectedCourse=courses.find(course=>course.key===teeChoice);
 const sorted=rounds.slice().sort((a,b)=>b.date.localeCompare(a.date));

 async function flushSave(){
  if(saveInFlight.current||!pendingSave.current)return;
  if(saveTimer.current){clearTimeout(saveTimer.current);saveTimer.current=null;}
  const snapshot=pendingSave.current;pendingSave.current=null;saveInFlight.current=true;
  let failed=false;
  try{await saveHandler.current(snapshot);if(!pendingSave.current){setSaveState('saved');if(snapshot.status==='complete'){try{localStorage.removeItem(cacheKey);}catch{}}}}
  catch(cause){failed=true;setSaveState('error');setError((cause as Error).message);pendingSave.current=snapshot;}
  finally{saveInFlight.current=false;if(pendingSave.current&&!failed)void flushSave();}
 }
 function cacheRound(round:RoundRecord){try{localStorage.setItem(cacheKey,JSON.stringify(round));}catch{}}
 function queueSave(next:RoundRecord,immediate=false){
  setActive(next);pendingSave.current=next;setSaveState('saving');setError('');cacheRound(next);
  if(saveTimer.current)clearTimeout(saveTimer.current);
  if(immediate)void flushSave();else saveTimer.current=setTimeout(()=>void flushSave(),450);
 }
 function cachedRound(source:RoundRecord){try{const cached=JSON.parse(localStorage.getItem(cacheKey)??'null') as RoundRecord|null;if(cached?.id===source.id&&(cached.clientUpdatedAt??'')>(source.clientUpdatedAt??''))return cached;}catch{}return source;}
 function resume(source:RoundRecord,hole?:number){const next=hydrateRound(cachedRound(source)),editingComplete=hole!==undefined&&inferRoundStatus(next)==='complete';setError('');setReview(null);setReviewPlayerId(next.players?.[0]?.id??'');setActive({...next,status:editingComplete?'complete':'active',activeHole:hole??next.activeHole??1});}
 function openReview(source:RoundRecord){const next=hydrateRound(source);setReview(next);setReviewPlayerId(next.players?.[0]?.id??'');setError('');}
 function beginSetup(){setSetup(blankRound(today()));setCourseChoice('__new');setTeeChoice('');setError('');}
 function applyCourse(course:CourseConfig){if(!setup)return;const count=Number(course.holeCount),players=(setup.players??[]).map(player=>({...player,scores:Array.from({length:count},()=>null)}));setSetup(hydrateRound({...setup,title:course.title,teeName:course.teeName,holeCount:course.holeCount,players,roundHoles:course.holes.map((hole,index)=>({hole:index+1,par:hole.par,distance:hole.distance,score:null}))}));}
 function chooseCourse(value:string){if(!setup)return;setCourseChoice(value);if(value==='__new'){setTeeChoice('');setSetup({...setup,title:'',teeName:'',roundHoles:setup.roundHoles.map(hole=>({...hole,par:4,distance:undefined}))});return;}const course=courseGroups.find(group=>group.key===value)?.options[0];if(!course)return;setTeeChoice(course.key);applyCourse(course);}
 function chooseTee(value:string){const course=courses.find(item=>item.key===value);if(!course)return;setTeeChoice(value);applyCourse(course);}
 function resizeSetup(value:'9'|'18'){if(!setup)return;const count=Number(value),players=(setup.players??[]).map(player=>({...player,scores:Array.from({length:count},(_,index)=>player.scores[index]??null)}));const template=selectedCourse?.holes??[];setSetup(hydrateRound({...setup,holeCount:value,players,roundHoles:Array.from({length:count},(_,index)=>{const preset=template[index]??(template.length===9?template[index%9]:undefined);return setup.roundHoles[index]??{hole:index+1,par:preset?.par??4,distance:preset?.distance,score:null};})}));}
 function changeSetupHole(index:number,patch:Partial<RoundHole>){if(!setup)return;setSetup({...setup,roundHoles:setup.roundHoles.map((hole,holeIndex)=>holeIndex===index?{...hole,...patch}:hole)});}
 function addPlayer(){if(!setup||(setup.players?.length??0)>=8)return;setSetup(hydrateRound({...setup,players:[...(setup.players??[]),{id:uid(),name:`Player ${(setup.players?.length??0)+1}`,scores:setup.roundHoles.map(()=>null)}]}));}
 function updatePlayer(id:string,name:string){if(!setup)return;setSetup({...setup,players:(setup.players??[]).map(player=>player.id===id?{...player,name}:player)});}
 function removePlayer(id:string){if(!setup||(setup.players?.length??0)<=1)return;setSetup(hydrateRound({...setup,players:(setup.players??[]).filter(player=>player.id!==id)}));}
 async function startRound(){if(!setup||!setup.title.trim()||!(setup.players??[]).every(player=>player.name.trim()))return;setSaving(true);setError('');try{const now=new Date().toISOString(),next=hydrateRound({...setup,title:setup.title.trim(),teeName:setup.teeName?.trim(),players:setup.players?.map(player=>({...player,name:player.name.trim()})),status:'active',activeHole:1,startedAt:now,clientUpdatedAt:now,done:false});await onSave(next);cacheRound(next);setSetup(null);setActive(next);setSaveState('saved');}catch(cause){setError((cause as Error).message);}finally{setSaving(false);}}
 function finishRound(next:RoundRecord){queueSave(next,true);setActive(null);openReview(next);}
 function exitActive(){void flushSave();setActive(null);}

 return <div className="rounds-surface"><div className="heading"><div><h2>Round tracker</h2><p className="muted">Fast on-course capture with review-ready performance data.</p></div><button className="button primary" onClick={beginSetup}><Plus size={16}/>Start a round</button></div>
  {!sorted.length?<section className="panel round-empty"><MapPinned size={34}/><h2>Your next round starts here.</h2><p className="muted">Set up the course and players, then score one hole at a time while you play.</p><button className="button primary" onClick={beginSetup}><Plus size={16}/>Set up a round</button></section>:<div className="round-list">{sorted.map(source=>{const round=hydrateRound(source),status=inferRoundStatus(round),summary=calculateRoundSummary(round),playerCount=round.players?.length??1;return <article className="panel round-card" key={round.id}><div className="round-date"><span>{new Date(round.date+'T12:00:00Z').getUTCDate()}</span>{new Date(round.date+'T12:00:00Z').toLocaleDateString('en-AU',{month:'short',timeZone:'UTC'}).toUpperCase()}</div><main><div className="round-card-head"><div><span className="badge">{round.holeCount} HOLES · {status==='complete'?'COMPLETE':'IN PROGRESS'}</span><h2>{round.title}</h2><span className="muted">{pretty(round.date)}{round.teeName?` · ${round.teeName} tees`:''} · {playerCount} {playerCount===1?'player':'players'}</span></div><button className={`button small ${status==='active'?'primary':''}`} onClick={()=>status==='active'?resume(round):openReview(round)}>{status==='active'?<><RotateCcw/>Resume</>:<>Review<ChevronRight/></>}</button></div><div className="round-mini-grid"><div><span>HOLES</span><strong>{summary.holesCompleted}/{round.holeCount}</strong></div><div><span>YOUR SCORE</span><strong>{summary.holesCompleted?summary.totalScore:'—'}</strong></div><div><span>TO PAR</span><strong className={summary.toPar<0?'under':''}>{summary.holesCompleted?signed(summary.toPar):'—'}</strong></div><div><span>PUTTS</span><strong>{summary.holesWithPutts?summary.totalPutts:'—'}</strong></div><div><span>PENALTIES</span><strong>{summary.holesCompleted?summary.penalties:'—'}</strong></div></div>{round.notes&&<p className="muted">{round.notes}</p>}</main></article>;})}</div>}

  <Dialog open={!!setup} onOpenChange={open=>{if(!open&&!saving)setSetup(null);}}><DialogContent className="round-modal setup-modal"><DialogTitle>Set up round</DialogTitle><DialogDescription>Choose the course, then the tees. Confirm the card and add the group before starting.</DialogDescription>{setup&&<form onSubmit={event=>{event.preventDefault();void startRound();}}><div className="setup-section"><span className="setup-step">1</span><div className="setup-section-body"><h3>Course and tees</h3><div className="round-meta">{courses.length>0&&<label className="field">Course<Select value={courseChoice} onValueChange={chooseCourse}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__new">Create a new course</SelectItem>{courseGroups.map(group=><SelectItem key={group.key} value={group.key}>{group.title}</SelectItem>)}</SelectContent></Select></label>}{courseChoice==='__new'?<><label className="field">Course name<input required maxLength={200} placeholder="e.g. Boomerang Farm" value={setup.title} onChange={event=>setSetup({...setup,title:event.target.value})}/></label><label className="field">Tees (optional)<input maxLength={80} placeholder="e.g. White" value={setup.teeName??''} onChange={event=>setSetup({...setup,teeName:event.target.value})}/></label></>:selectedGroup&&<label className="field">Tee / card<Select value={teeChoice} onValueChange={chooseTee}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{selectedGroup.options.map(course=><SelectItem key={course.key} value={course.key}>{course.teeName||'Standard card'}</SelectItem>)}</SelectContent></Select></label>}<label className="field">Date<input required type="date" max={today()} value={setup.date} onChange={event=>setSetup({...setup,date:event.target.value})}/></label><label className="field">Round length<Select value={setup.holeCount} onValueChange={value=>resizeSetup(value as '9'|'18')}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="9">9 holes</SelectItem><SelectItem value="18">18 holes</SelectItem></SelectContent></Select></label></div>{selectedCourse?.sourceUrl&&<p className="muted">Club course guide: <a href={selectedCourse.sourceUrl} target="_blank" rel="noopener noreferrer">check this scorecard</a>. Confirm the selected tee and pars before play.</p>}</div></div>
   <div className="setup-section"><span className="setup-step">2</span><div className="setup-section-body"><div className="sectionhead"><div><h3>Holes</h3><p className="muted">Confirm par. Distance is optional and stored internally in metres.</p></div><span className="badge">{setup.holeCount} HOLES</span></div><div className="setup-holes">{setup.roundHoles.map((hole,index)=><div className="setup-hole" key={hole.hole}><strong>{hole.hole}</strong><label>Par<select aria-label={`Hole ${hole.hole} par`} value={hole.par} onChange={event=>changeSetupHole(index,{par:Number(event.target.value)})}>{[3,4,5,6].map(par=><option key={par}>{par}</option>)}</select></label><label>{distanceLabel(distanceUnit)}<input aria-label={`Hole ${hole.hole} distance`} inputMode="numeric" type="number" min="0" max={distanceUnit==='yd'?1100:1000} placeholder="—" value={rounded(displayDistance(hole.distance,distanceUnit),0)??''} onChange={event=>changeSetupHole(index,{distance:event.target.value===''?undefined:storeDistance(Number(event.target.value),distanceUnit)})}/></label></div>)}</div></div></div>
   <div className="setup-section"><span className="setup-step">3</span><div className="setup-section-body"><div className="sectionhead"><div><h3>Players</h3><p className="muted">The first player is you and drives your analytics.</p></div><button type="button" className="button small" onClick={addPlayer} disabled={(setup.players?.length??0)>=8}><UserPlus/>Add player</button></div><div className="player-list">{(setup.players??[]).map((player,index)=><div className="player-name" key={player.id}><Users/><input required maxLength={50} aria-label={`Player ${index+1} name`} value={player.name} onChange={event=>updatePlayer(player.id,event.target.value)}/>{index===0?<span className="badge">YOU</span>:<button type="button" className="iconbtn" aria-label={`Remove ${player.name}`} onClick={()=>removePlayer(player.id)}><X/></button>}</div>)}</div><label className="field setup-notes">Round notes<input maxLength={5000} placeholder="Conditions, focus, competition…" value={setup.notes} onChange={event=>setSetup({...setup,notes:event.target.value})}/></label></div></div>
   {error&&<div className="error" role="alert">{error}</div>}<div className="setup-actions"><button className="button" type="button" onClick={()=>setSetup(null)}>Cancel</button><button className="button primary" type="submit" disabled={saving||!setup.title.trim()||!(setup.players??[]).every(player=>player.name.trim())}><Flag/>{saving?'Starting…':'Start round'}</button></div></form>}</DialogContent></Dialog>

  <Dialog open={!!active} onOpenChange={open=>{if(!open)exitActive();}}>{active&&<DialogContent className="active-round-modal" showCloseButton={false}><DialogTitle className="sr-only">Active round at {active.title}</DialogTitle><DialogDescription className="sr-only">Record one hole at a time. Changes save automatically.</DialogDescription><ActiveRound round={active} distanceUnit={distanceUnit} saveState={saveState} onChange={queueSave} onFinish={finishRound} onExit={exitActive}/></DialogContent>}</Dialog>

  <Dialog open={!!review} onOpenChange={open=>{if(!open&&!saving)setReview(null);}}><DialogContent className="round-modal review-modal">{review&&<ReviewRound round={review} playerId={reviewPlayerId||review.players?.[0]?.id||''} setPlayerId={setReviewPlayerId} pretty={pretty} distanceUnit={distanceUnit} onEditHole={(hole)=>resume(review,hole)} onDelete={()=>{onDelete(review);setReview(null);}}/>}</DialogContent></Dialog>
 </div>;
}

function ReviewRound({round,playerId,setPlayerId,pretty,distanceUnit,onEditHole,onDelete}:{round:RoundRecord;playerId:string;setPlayerId:(id:string)=>void;pretty:(date:string)=>string;distanceUnit:DistanceUnit;onEditHole:(hole:number)=>void;onDelete:()=>void}){
 const summary=calculateRoundSummary(round,playerId),player=round.players?.find(item=>item.id===playerId)??round.players?.[0];
 return <><DialogTitle>{round.title}</DialogTitle><DialogDescription>{pretty(round.date)}{round.teeName?` · ${round.teeName} tees`:''} · {round.holeCount} holes</DialogDescription>{(round.players?.length??0)>1&&<div className="review-player-tabs">{round.players?.map(item=><button type="button" key={item.id} className={item.id===player?.id?'active':''} onClick={()=>setPlayerId(item.id)}>{item.name}</button>)}</div>}<div className="review-hero"><div><span>SCORE</span><strong>{summary.totalScore||'—'}</strong><small>{summary.holesCompleted?`${signed(summary.toPar)} to par`:'No completed holes'}</small></div><div><span>HOLES</span><strong>{summary.holesCompleted}</strong><small>of {round.holeCount}</small></div><div><span>PUTTS</span><strong>{summary.holesWithPutts?summary.totalPutts:'—'}</strong><small>{summary.threePutts} three-putts</small></div><div><span>PENALTIES</span><strong>{summary.penalties}</strong><small>{summary.blowUpHoles} blow-up holes</small></div></div>
 <section className="review-stats"><div className="sectionhead"><div><span className="eyebrow">PERFORMANCE</span><h3>What was captured</h3></div></div><div className="review-stat-grid"><div><span>TEE SHOTS IN PLAY</span><strong>{summary.teeShotsTracked?`${Math.round(summary.teeInPlay/summary.teeShotsTracked*100)}%`:'—'}</strong><small>{summary.teeInPlay}/{summary.teeShotsTracked} tracked</small></div><div><span>LEFT / RIGHT</span><strong>{summary.teeLeft} / {summary.teeRight}</strong><small>directional misses</small></div><div><span>OB / WATER</span><strong>{summary.teeOb} / {summary.teeWater}</strong><small>tee outcomes</small></div><div><span>PUTTS / HOLE</span><strong>{summary.holesWithPutts?(summary.totalPutts/summary.holesWithPutts).toFixed(1):'—'}</strong><small>{summary.holesWithPutts} holes tracked</small></div>{([3,4,5] as const).map(par=><div key={par}><span>PAR {par} AVERAGE</span><strong>{summary.parAverages[par]?.toFixed(1)??'—'}</strong><small>completed holes</small></div>)}{Object.entries(summary.penaltiesByClub).map(([club,count])=><div key={club}><span>{club.toUpperCase()} PENALTIES</span><strong>{count}</strong><small>attributed from shots</small></div>)}</div></section>
 <section className="review-card"><div className="sectionhead"><div><span className="eyebrow">FULL SCORECARD</span><h3>{player?.name}</h3></div><span className="badge">TAP A HOLE TO EDIT</span></div><div className="review-holes">{round.roundHoles.map((hole,index)=>{const stat=getPlayerHoleStat(round,index,player?.id??'');return <button type="button" key={hole.hole} onClick={()=>onEditHole(hole.hole)}><span className="review-hole-number">{hole.hole}</span><span><small>PAR</small>{hole.par}</span><span><small>DIST</small>{hole.distance!==undefined?<>{rounded(displayDistance(hole.distance,distanceUnit),0)}{distanceLabel(distanceUnit)}</>:'—'}</span><strong>{stat?.score??'—'}<small>{stat?.score!==null&&stat?.score!==undefined?signed(stat.score-hole.par):''}</small></strong><span><small>PUTTS</small>{stat?.putts??'—'}</span><span><small>PEN</small>{stat?.penalties??0}</span><Pencil/></button>;})}</div></section>
 <div className="review-actions"><button type="button" className="button danger" onClick={onDelete}><Trash2/>Delete round</button><button type="button" className="button primary" onClick={()=>onEditHole(Math.max(1,round.activeHole??1))}><Pencil/>Edit holes</button></div></>;
}
